<?php
/**
 * Created by PhpStorm.
 * User: Alejandro
 * Date: 03.07.2017
 * Time: 0:38
 */

namespace app\components;


use yii\base\Widget;

class FormWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        return $this->render('form');
    }
}