<?php

namespace app\components;

use yii\base\Widget;
use app\models\Inbox;

class InboxWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $inmails = new Inbox();
        $allinbox =  $inmails->getMail(); //получаем все входящие письма в виде массива

        return $this->render('inbox', ['allinbox' => $allinbox]);
    }
}