<?php
/**
 * Created by PhpStorm.
 * User: Alejandro
 * Date: 03.07.2017
 * Time: 18:30
 */

namespace app\components;


use yii\base\Widget;
use app\models\Sent;

class SentWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $sentmsg = Sent::find()->asArray()->all(); //выборка в массив
        return $this->render('sent',  ['sentmsg' => $sentmsg]);
    }
}